gems:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - config.rb
  - bower.json
  - package.json
  - node_modules
  - gulpfile.js
  - Vagrantfile
  - .vagrant

defaults:
  - scope:
      path: releases
      type: pages
    values:
      layout: "release"
      changefreq: monthly
  - scope:
      path: "documentation"
      type: pages
    values:
      layout: doc-page
      priority: 0.8
  - scope:
      path: "news"
    values:
      layout: "default"
      category: "news"
      priority: 0.8

markdown: kramdown
sass:
  style: compressed

kramdown:
  input: kramdown
  hard_wrap: false
